add graphql api
DataJunction/datajunction pull request #199
Opened 2022-10-01 03:06 UTC by CircArgs

This PR seeks to address https://github.com/DataJunction/datajunction/issues/154

Using [strawberry](https://strawberry.rocks/) wrapping the sqlmodel pydantic models used in the rest api it gives a graphql api accessible with the example at `localhost:8000/graphql`

Here are some examples

```graphql
{
  getDatabases {
    id
    queries{
      id
      submittedQuery
    }
    name
    description
    URI
    createdAt
    extraParams
    cost
    tables {
      id
      databaseId
      node {
        id
        type
        tables{
          id
          columns {
            id
          }
        }
      }
    }
  }
}
```

```graphql
{
  getNodes {
    name
    type
  }
}
```

```graphql
mutation{
  submitQuery(
    createQuery: {databaseId: 2, submittedQuery: "select count(*) from comments"}
  ) {
    id
    submittedQuery
    executedQuery
    results{
      _Root__{
        rows
        rowCount
      }
    }
  }
}
```

```graphql
{
  readMetrics{
    name
    id
  }
}
```

```graphql
{
  readMetricsData(nodeId:4){
    id
  }
}
```

```graphql
{
  readMetricsSql(nodeId:4){
    sql
    databaseId
  }
}
```

2022-10-02 23:05 UTC, samredai commented
_request_
```gql
{
  readMetricsSql(nodeId:10, d: "basic.transform.country_agg.country", f: "basic.transform.country_agg.country='Brazil'"){
    sql
    databaseId 
  }
}
```
_response_
```json
{
  "data": {
    "readMetricsSql": {
      "sql": "SELECT sum(\"basic.transform.country_agg\".num_users) AS sum_1, \"basic.transform.country_agg\".country \nFROM (SELECT \"basic.source.users\".country AS country, count(\"basic.source.users\".id) AS num_users \nFROM (SELECT basic.dim_users.id AS id, basic.dim_users.full_name AS full_name, basic.dim_users.age AS age, basic.dim_users.country AS country, basic.dim_users.gender AS gender, basic.dim_users.preferred_language AS preferred_language \nFROM basic.dim_users) AS \"basic.source.users\" GROUP BY \"basic.source.users\".country) AS \"basic.transform.country_agg\" \nWHERE \"basic.transform.country_agg\".country = 'Brazil' GROUP BY \"basic.transform.country_agg\".country",
      "databaseId": 3
    }
  }
}
```
---
_request_
```gql
{
  readMetricsData(nodeId:10, d: "basic.transform.country_agg.country", f: "basic.transform.country_agg.country='Brazil'"){
    databaseId
    results {
      _Root__ {
        rows
      }
    }
  }
}
```
_response_
```json
{
  "data": {
    "readMetricsData": {
      "databaseId": 3,
      "results": {
        "_Root__": [
          {
            "rows": [
              [
                "Decimal('1')",
                "'Brazil'"
              ]
            ]
          }
        ]
      }
    }
  }
}
```
VERY cool! 😃

2022-10-06 06:04 UTC, agorajek requested changes
@CircArgs thank you so much for this PR! This plays very well into our vision of making DJ api available to a wide variety of clients. 

![so_good](https://user-images.githubusercontent.com/371403/194225806-c87f1090-c275-43b0-bfb6-0e409aa9a472.gif)

I just have left few minor comments in-line but after that I think we can merge it. I think our next problem to solve will be writing some good tests to make sure that both APIs (internal + graphQL) are kept in sync as we develop this system, but we can cross that bridge when we get there.

2022-10-06 16:35 UTC, CircArgs commented on src/datajunction/api/graphql/table.py
> +    Nodes can data in multiple tables, in different databases.
Done!

2022-10-06 16:37 UTC, CircArgs commented on src/datajunction/api/main.py
> +from webbrowser import get
I don't really know where this came from 😕 maybe my ide. removed it though

2022-10-06 16:37 UTC, CircArgs commented on src/datajunction/api/graphql/query.py
> +class Query_:
This is the one I don't think I can implement at least directly. I think the underscore is necessary to differentiate the type from the Grapqhl root `Query` type

2022-10-06 16:37 UTC, CircArgs commented on src/datajunction/api/graphql/database.py
> +    """a source database"""
Done!

2022-10-06 16:37 UTC, CircArgs commented on src/datajunction/api/graphql/column.py
> +from sqlalchemy.sql.schema import Column as SqlaColumn
Nope my bad

2022-10-07 03:34 UTC, agorajek commented on src/datajunction/api/graphql/query.py
> +class Query_:
I see. I don't have an opinion on a better option then, but maybe @betodealmeida has.

2022-10-07 03:37 UTC, agorajek approved these changes

2022-10-07 16:31 UTC, merged